from .schemas import ScenarioCard, TargetZone

SEEDS: dict[str, ScenarioCard] = {
    "deadline-with-manager": ScenarioCard(
        name="Срок задачи с руководителем",
        domain="Работа в команде",
        topic="Команда не укладывается в срок релиза",
        difficulty="medium",
        tone="strict",
        method="harvard",
        style="hard",
        user_role="Младший аналитик",
        user_goal="Перенести срок сдачи отчёта с 5 до 12 рабочих дней без потери задачи",
        opponent_role="Руководитель отдела",
        opponent_goal="Получить отчёт как можно раньше, отчёт нужен к совещанию с директором",
        opponent_hidden_interests=["на совещании достаточно предварительной версии", "боится выглядеть неготовым перед директором"],
        opponent_batna="Отдать задачу опытному коллеге, который перегружен",
        user_batna="Сделать в срок урезанную версию без проверки данных",
        target_zone=TargetZone(unit="рабочих дней", user_start=12, zone_min=8, zone_max=10, opponent_start=5),
        mandatory_details=["данные от смежного отдела приходят с опозданием", "предварительная версия к совещанию"],
        context="Отчёт по оттоку клиентов. Данные от смежного отдела запаздывают на три дня.",
        max_turns=10,
    ),
    "price-with-client": ScenarioCard(
        name="Цена и объём работ с заказчиком",
        domain="Проектная работа",
        topic="Заказчик просит скидку на разработку",
        difficulty="medium",
        tone="skeptical",
        method="spin",
        style="pressing",
        user_role="Исполнитель, фрилансер",
        user_goal="Сохранить цену не ниже 180 тысяч, при скидке — сократить объём",
        opponent_role="Директор небольшой компании",
        opponent_goal="Заплатить меньше 150 тысяч за тот же объём",
        opponent_hidden_interests=["главное — успеть до проверки через месяц", "уже потратил бюджет на другого подрядчика"],
        opponent_batna="Нанять студента за 100 тысяч без гарантий",
        user_batna="Взять другой проект за 160 тысяч",
        target_zone=TargetZone(unit="тыс. руб.", user_start=200, zone_min=160, zone_max=185, opponent_start=130),
        mandatory_details=["что входит в объём работ", "срок до проверки"],
        context="Нужна автоматизация отчётности. Прошлый подрядчик не справился.",
        max_turns=10,
    ),
}
